-   id: commit-msg-format
    name: Commit Message Format
    description: "Pre-receive hook to validate commit message structure"
    entry: commit-msg-format
    language: python
    files: ''
    stages: [push]
    minimum_pre_commit_version: 0.15.4
-   id: commit-message
    name: Commit Message Format Part Deux
    description: "Commit-msg hook to validate commit message structure"
    entry: commit-message
    language: python
    files: ''
    stages: [commit-msg]
    minimum_pre_commit_version: 0.15.4